<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Rafferty Parker and Ben Anderson (ben.anderson@otago.ac.nz), Centre for Sustainability, University of Otago" />


<title>Analysis of electric vehicle usage patterns in New Zealand</title>

<script src="EVBB_report_v2_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="EVBB_report_v2_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="EVBB_report_v2_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="EVBB_report_v2_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="EVBB_report_v2_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="EVBB_report_v2_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="EVBB_report_v2_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="EVBB_report_v2_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="EVBB_report_v2_files/navigation-1.1/tabsets.js"></script>
<script src="EVBB_report_v2_files/navigation-1.1/codefolding.js"></script>
<link href="EVBB_report_v2_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="EVBB_report_v2_files/highlightjs-9.12.0/highlight.js"></script>
<script src="EVBB_report_v2_files/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Analysis of electric vehicle usage patterns in New Zealand</h1>
<h3 class="subtitle">Statistical Report</h3>
<h4 class="author">Rafferty Parker and Ben Anderson (<a href="mailto:ben.anderson@otago.ac.nz" class="email">ben.anderson@otago.ac.nz</a>), <a href="https://www.otago.ac.nz/centre-sustainability/">Centre for Sustainability</a>, University of Otago</h4>
<h4 class="date">Last run at: 2019-07-04 10:26:05</h4>

</div>


<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>The New Zealand government has set a target of increasing the number of electric vehicles (EVs) in New Zealand to 64,000 by 2021 <span class="citation">(Transpower New Zealand 2017)</span>. High penetration of EVs would cause EV recharging to contribute a substantial portion of total electricity load. A report prepared for lines companies Orion, Powerco and Unison by Concept Consulting Group entitled “Driving change - Issues and options to maximise the opportunities from large-scale electric vehicle uptake in New Zealand” predicts that if all current light private vehicles were electric, annual residential electricity consumption would increase by approximately 30%, whereas if all vehicles including trucks were electric, this would increase the total electricity consumption of New Zealand by approximately 41% <span class="citation">(Concept Consulting 2018)</span>.</p>
<p>New Zealand’s total electricity demand varies throughout the day, with weekdays in particular having two distinct “peaks”; one in the morning, and one in the evening <span class="citation">(Transpower New Zealand 2015)</span>. Providing the electricity to meet these demand peaks is a costly and inefficient process <span class="citation">(Khan, Jack, and Stephenson 2018)</span>. Concurrent electric vehicle charging, especially in the early evening when many motorists return home <span class="citation">(Speidel and Bräunl 2014, @langbroek_when_2017)</span>, would have the potential to negatively impact the operation of the grid through drastically increasing peak loads <span class="citation">(Azadfar, Sreeram, and Harries 2015, @langbroek_when_2017)</span>, leading to an increased cost of electricity due to the requirement of expensive upgrades to the electricity grid <span class="citation">(Stephenson et al. 2017)</span>.</p>
<p>The Concept Consulting report considers different methods of EV charging in its models. The assumption that most drivers would begin charging immediately after returning home is referred to as “passive” charging, while charging that is programmed (either by the driver or by an external entity) to occur during off-peak periods is referred to as “smart”. The modelling undertaken in the Concept Consulting report suggests that under a scenario whereby 57% of the current private vehicle fleet were EVs (corresponding to one EV per household), passive charging would cause an increase of peak electricity demand of approximately 3,000MW, whereas if all were charged in a “smart” fashion, there would be no increase in peak demand.</p>
<p>This report extends the work done by Concept Consulting, but utilises actual data collected from electric vehicles, as opposed to using models based on the current New Zealand transport sector. The intention of the report is to provide further insight into the potential effects on the New Zealand electricity grid that may occur with a dramatic increase in EVs, so that these may be planned for and mitigated. It is also inspired by the <a href="https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/764270/electric-chargepoint-analysis-2017-domestics.pdf">UK Department of Transport 2018 statistical report</a> <span class="citation">(Eyers 2018)</span>.</p>
</div>
<div id="data" class="section level1">
<h1><span class="header-section-number">2</span> Data</h1>
<div id="background" class="section level2">
<h2><span class="header-section-number">2.1</span> Background</h2>
<p>The data used has been provided by ‘Flip the Fleet’, a community organisation that hopes to increase uptake of electric vehicles in New Zealand. Flip the Fleet have been collecting data on electric vehicle usage patterns, via Exact IOT Limited’s <a href="https://flipthefleet.org/ev-black-box/">blackbox recorder</a>, a small electronic device that connects to the vehicle’s internal computer and sends detailed data about the battery health, power demand, charging rate, speed and other performance information to a secure database.</p>
</div>
<div id="cleaning" class="section level2">
<h2><span class="header-section-number">2.2</span> Initial cleaning</h2>
<p>The subset of this data provided to the University of Otago was collected from 52 domestic electric vehicles monitored from April 2018 to March 2019. The data consisted of 1,882,040 1 minute interval observations of timestamped odometer readings (in km) together with measurements of charging power (kW) and battery charge state (% charged) linked to a unique anonymised vehicle identifier.</p>
<p>There are a number of important limitations to this data:</p>
<ul>
<li>measurement of observations only occurs when the car is switched on and/or plugged in and charging. As a result no data will be collected when the EV is switched off. This means that there are large non-erroneous ‘gaps’ in the data which represent ‘no charging’ (and also ‘no driving’) but which are not included as ‘0 power demand’ in the analyses since to do so would require imputation of a very large number of missing time stamps for each vehicle. This means we are only really able to analyse power demand profiles for vehicles that were charging, <em>not for all vehicles in all time periods</em>;</li>
<li>data upload relied on mobile 3G data signal and the extent to which gaps in the data are due to data upload errors rather than vehicle non-use (as above) is currently unclear;</li>
<li>these vehicles are driven by ‘early adopters’ who have opted to install the measuring devices in order to collect their vehicle usage data. As a result the data may not be representative of the usage patterns of current or future EV drivers <span class="citation">(Rezvani, Jansson, and Bodin 2015, @li_review_2017)</span>.</li>
</ul>
<p>Even though the use of an anonymised vehicle identifier should prevent the identification of the vehicles in the sample, the fine-grained temporal nature of the data and the relatively small population of EV owners from whom the sample is drawn (Flip The Fleet members) means that the data cannot be publicly released.</p>
<p>Figure <a href="#fig:initialDataChecksPlotTile">2.1</a> shows the number of unique EVs observed by time of day and date. As we can see the early part of the sample is sparse and indeed the maximum number of EVs observed in any 15 minute time period was only 22 out of a possible total of 52. While this will not affect some analyses, it is likely to introduce error and small sample effects to summary analyses (e.g. means) or month by month analyses. In some sections the analysis will therefore be restricted to the data from September to March.</p>
<div class="figure"><span id="fig:initialDataChecksPlotTile"></span>
<img src="EVBB_report_v2_files/figure-html/initialDataChecksPlotTile-1.png" alt="Number of unique EVs observed by time of day and date" width="672" />
<p class="caption">
Figure 2.1: Number of unique EVs observed by time of day and date
</p>
</div>
<p>Figure <a href="#fig:initialDataChecksPlotDate">2.2</a> shows the unique number of EVs recorded on each day and reflects the period over which Flip The Fleet installed the data collection boxes.</p>
<div class="figure"><span id="fig:initialDataChecksPlotDate"></span>
<img src="EVBB_report_v2_files/figure-html/initialDataChecksPlotDate-1.png" alt="Number of unique EVs observed by time of day and date" width="672" />
<p class="caption">
Figure 2.2: Number of unique EVs observed by time of day and date
</p>
</div>
<p>Finally, <a href="#tab:noObsEVs">2.1</a> shows that a small number of EVs have very few observations, in some cases not extending beyond 1 day (shown as 0 days observed).</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:noObsEVs">Table 2.1: </span>Number of observations and start/end dates for vehicles (6 most scarce)
</caption>
<thead>
<tr>
<th style="text-align:left;">
id
</th>
<th style="text-align:right;">
nObs
</th>
<th style="text-align:left;">
startTime
</th>
<th style="text-align:left;">
endTime
</th>
<th style="text-align:right;">
meanWhCharging
</th>
<th style="text-align:right;">
maxWhCharging
</th>
<th style="text-align:left;">
nDaysObserved
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
0cc746a3f5ae75ee94068a8354b6be08
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
2018-09-09 10:46:30
</td>
<td style="text-align:left;">
2018-09-09 10:48:42
</td>
<td style="text-align:right;">
0.0000000
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:left;">
0 days
</td>
</tr>
<tr>
<td style="text-align:left;">
01583b8a5f0344cc4aa3b3939a27af2a
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
2018-09-09 10:34:12
</td>
<td style="text-align:left;">
2018-09-09 10:36:25
</td>
<td style="text-align:right;">
0.0000000
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:left;">
0 days
</td>
</tr>
<tr>
<td style="text-align:left;">
4a6bb6e7ffc28d9d8eda7b4c6377a027
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:left;">
2018-09-08 08:48:38
</td>
<td style="text-align:left;">
2018-09-09 10:27:50
</td>
<td style="text-align:right;">
4.2251742
</td>
<td style="text-align:right;">
27.557201
</td>
<td style="text-align:left;">
1 days
</td>
</tr>
<tr>
<td style="text-align:left;">
126c8759ec95ba40070b16a11fe0e587
</td>
<td style="text-align:right;">
258
</td>
<td style="text-align:left;">
2018-09-30 11:54:18
</td>
<td style="text-align:left;">
2018-09-30 19:24:05
</td>
<td style="text-align:right;">
1.5869526
</td>
<td style="text-align:right;">
1.960213
</td>
<td style="text-align:left;">
0 days
</td>
</tr>
<tr>
<td style="text-align:left;">
6e3293c77f562262ed6608db1b596d36
</td>
<td style="text-align:right;">
4315
</td>
<td style="text-align:left;">
2018-05-15 14:48:15
</td>
<td style="text-align:left;">
2018-12-06 13:25:56
</td>
<td style="text-align:right;">
0.2872577
</td>
<td style="text-align:right;">
47.245786
</td>
<td style="text-align:left;">
205 days
</td>
</tr>
<tr>
<td style="text-align:left;">
781f06f7d7bb80b74c399326be0d3e28
</td>
<td style="text-align:right;">
5469
</td>
<td style="text-align:left;">
2018-09-28 11:25:58
</td>
<td style="text-align:left;">
2018-10-15 16:21:57
</td>
<td style="text-align:right;">
2.3686450
</td>
<td style="text-align:right;">
47.687105
</td>
<td style="text-align:left;">
17 days
</td>
</tr>
</tbody>
</table>
<p>Taking all of the above into account we have therefore discarded:
#FIX: r nrow(summaryDT) - nrow(includeDT)
* the FIX vehicles that had no recorded <em>charging</em> observations (this also discarded those with very few observations - see Table <a href="#tab:noObsEVs">2.1</a>);
* 45 instances of charging power greater than 120kW. These were considered anomalies and as these exceed the capacity of the highest charging stations currently available in New Zealand <span class="citation">(Concept Consulting 2018)</span>;
* 61 instances of battery state of charge observations of greater than 100%;
* all observations collected before 1st October and after 1st March in order to focus analysis on the periods with most EVs present in the data. It is hoped that this will reduce the extent to which the charging behaviour of a small number of EV owners will skew the aggregated results.</p>
<p>This left 45 remaining vehicles, and 1,381,565 observations as shown in Table <a href="#tab:finalTable">2.2</a>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:finalTable">Table 2.2: </span>Number of observations by charge flag (final cleaned data)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Weekdays
</th>
<th style="text-align:right;">
Weekends
</th>
<th style="text-align:right;">
NA
</th>
<th style="text-align:right;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:right;">
5091
</td>
<td style="text-align:right;">
2358
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7449
</td>
</tr>
<tr>
<td style="text-align:left;">
Not charging
</td>
<td style="text-align:right;">
452288
</td>
<td style="text-align:right;">
124203
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
576491
</td>
</tr>
<tr>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:right;">
592585
</td>
<td style="text-align:right;">
205040
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
797625
</td>
</tr>
<tr>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Sum
</td>
<td style="text-align:right;">
1049964
</td>
<td style="text-align:right;">
331601
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1381565
</td>
</tr>
</tbody>
</table>
</div>
<div id="definitions" class="section level2">
<h2><span class="header-section-number">2.3</span> Definitions and preparation</h2>
<div id="chargeType" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Charge type</h3>
<p>Charging data has been broadly separated into two separate categories, ‘Standard’ and ‘Fast’. Standard charging is defined to be when the charger is reading less than 7kW - this is considered the upper limit of ordinary home charging without an expensive wiring upgrade <span class="citation">(Concept Consulting 2018)</span>. Fast charging is all charging equal to or greater than 7kW, and would likely occur at designated and purpose-built public charging stations.</p>
<p>It should be noted that this method is not always accurate since we can identify apparent sequences of charging which start at &gt; 7kW and decline to &lt; 7kW over a relatively short period or vice versa (see Section <a href="#chargeFlagTest">5.2.1</a>). In this circumstance the first observation will be correctly classified as ‘Fast’ but the lower observations, which we assume are lower power ‘top-ups’ at the end of a fast charge will be incorrectly classified as ‘Standard’. As an example, we know that there are 92 sequences of charging events (out of a total of 14683) where the first and last charge types do not match.</p>
<p>This is clarified and corrected in Section <a href="#codeSequences">2.3.2</a> for charging begin/end pairs (and thus in the results that use this data) but has yet to be resolved in other sections which use all charging observations. As a result we may currently be <em>under-estimating</em> the number of fast charge observations and <em>over-estimating</em> the mean power demand of standard charges where we conduct analysis using all charging observations.</p>
<p>Figure <a href="#fig:obsPower">2.3</a> shows the distribution of observed charging kW demand by inferred charge type without correcting for potential mis-classifications. Setting aside the small number of potential misclassifications noted above, the plot confirms the validity of our definition and shows that fast charges were relatively rare in the dataset. Fast charges have two distinct power demand ‘peaks’ at ~22kW and ~45kW while the far more common standard charging was mostly concentrated around 1.8kW and 3kW, with a smaller concentration around 6kW.</p>
<div class="figure"><span id="fig:obsPower"></span>
<img src="EVBB_report_v2_files/figure-html/obsPower-1.png" alt="Observed power demand distribution by charge type where charging observed" width="672" />
<p class="caption">
Figure 2.3: Observed power demand distribution by charge type where charging observed
</p>
</div>
</div>
<div id="codeSequences" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Charge sequences</h3>
<p>In order to determine charging durations, we have identified and extracted observations which are the start and end of charging sequences. This is done using the following logic:</p>
<ul>
<li>rows were coded as “charging begins” if the charging power was greater than zero and the previous and following row’s charging power were (respectively) equal to zero and greater than zero;</li>
<li>rows were coded as “charge ends” if the charging power was greater than zero and the previous and following row’s charging power were (respectively) greater than zero and equal to zero;</li>
<li>rows were coded as “charge in a sequence” if charging power &gt; 0 and the observations either side were also &gt; 0</li>
<li>rows were coded as “single charge events” if charging power &gt; 0 but the observations either side were 0.</li>
</ul>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:seqCodeTable">Table 2.3: </span>Charge sequence coding results (all cleaned data)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Fast charging
</th>
<th style="text-align:right;">
Not charging
</th>
<th style="text-align:right;">
Standard charging
</th>
<th style="text-align:right;">
NA
</th>
<th style="text-align:right;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Charging in a seq
</td>
<td style="text-align:right;">
6555
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
778592
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
785147
</td>
</tr>
<tr>
<td style="text-align:left;">
First charge obs in a seq
</td>
<td style="text-align:right;">
413
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6928
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7341
</td>
</tr>
<tr>
<td style="text-align:left;">
Last charge in a seq
</td>
<td style="text-align:right;">
350
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6992
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7342
</td>
</tr>
<tr>
<td style="text-align:left;">
Not charging (0 kW)
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
576491
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
576491
</td>
</tr>
<tr>
<td style="text-align:left;">
Single charge observation
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5111
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5241
</td>
</tr>
<tr>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Sum
</td>
<td style="text-align:right;">
7449
</td>
<td style="text-align:right;">
576491
</td>
<td style="text-align:right;">
797625
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1381565
</td>
</tr>
</tbody>
</table>
<p>Table <a href="#tab:seqCodeTable">2.3</a> shows the results of this coding for all clean observations within the selected dates (2018-10-01 - 2019-02-27). As we can see most observations were coded using this scheme and we obtained 7,341 instances of charging starting, and 7,342 instances of charge ending. The additional 1 instances of charge ending than there are of the charge beginning may be due to the first (or last) instance of data collection occurring during mid-charge for some vehicles.</p>
<p>An alternative classification method, tested in Section <a href="#chargeFlagTest">5.2.1</a>, added a 120 second maximim threshold to sequences of observations but was not used as it failed to identify sparse sequences of charging events.</p>
<p>Comparison of the begining and end charge types showed, as suspected, that a number of pairs had mis-matching charge-types (see Table <a href="#tab:checkChargeTypeErrors">2.4</a>). In all cases charge type was set to ‘Fast’ if either of the start or end observations was classified as ‘Fast’. However this correction has only been made with the extracted pairs data and how not yet been applied to the full ‘all observations’ data.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:checkChargeTypeErrors">Table 2.4: </span>Charge type errors detected via mis-matching start and end observations vs uncorrected charge type
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Fast charging
</th>
<th style="text-align:right;">
Standard charging
</th>
<th style="text-align:right;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Error: first = Fast, last = Standard
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
77
</td>
</tr>
<tr>
<td style="text-align:left;">
Error: first = Standard, last = Fast
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
OK: first = Fast, last = Fast
</td>
<td style="text-align:right;">
336
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
336
</td>
</tr>
<tr>
<td style="text-align:left;">
OK: first = Standard, last = Standard
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6913
</td>
<td style="text-align:right;">
6913
</td>
</tr>
<tr>
<td style="text-align:left;">
Sum
</td>
<td style="text-align:right;">
413
</td>
<td style="text-align:right;">
6928
</td>
<td style="text-align:right;">
7341
</td>
</tr>
</tbody>
</table>
<p>The charge duration was then calculated as being the time duration between each pair of ‘first in charge sequence’ and ‘last in charge sequence’ observations.</p>
<p>Figure <a href="#fig:durationHist">2.4</a> shows the overall distribution of all charging sequences using the corrected charge type. Clearly there are very small and a few very large values for both charging types.</p>
<div class="figure"><span id="fig:durationHist"></span>
<img src="EVBB_report_v2_files/figure-html/durationHist-1.png" alt="Duration of charging sequences by corrected charge type" width="672" />
<p class="caption">
Figure 2.4: Duration of charging sequences by corrected charge type
</p>
</div>
<p>Table <a href="#tab:durationDescTable">2.5</a> shows the overall distributions and indicates the extent to which the means are skewed by the very small and a few very large values shown in Figure <a href="#fig:durationHist">2.4</a>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:durationDescTable">Table 2.5: </span>Duration of all charge sequences by charge type
</caption>
<thead>
<tr>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:right;">
N
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:right;">
6907
</td>
<td style="text-align:left;">
103.32 mins
</td>
<td style="text-align:right;">
3.43
</td>
<td style="text-align:left;">
0.27 mins
</td>
<td style="text-align:left;">
3029.12 mins
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:right;">
427
</td>
<td style="text-align:left;">
24.58 mins
</td>
<td style="text-align:right;">
14.25
</td>
<td style="text-align:left;">
0.02 mins
</td>
<td style="text-align:left;">
922.03 mins
</td>
</tr>
</tbody>
</table>
<p>Table <a href="#tab:durationLongTableStd">2.6</a> shows the longest duration ‘standard’ charge events while Table <a href="#tab:durationLongTableFast">2.7</a> shows the longest duration ‘fast’ charge events.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:durationLongTableStd">Table 2.6: </span>Duration of longest charge sequences (Standard charging)
</caption>
<thead>
<tr>
<th style="text-align:left;">
dvID
</th>
<th style="text-align:left;">
startTime
</th>
<th style="text-align:left;">
day_of_week
</th>
<th style="text-align:left;">
chargeType
</th>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:left;">
pairDuration
</th>
<th style="text-align:right;">
duration_hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Vehicle 37
</td>
<td style="text-align:left;">
06:33:33
</td>
<td style="text-align:left;">
Saturday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
3029.12 mins
</td>
<td style="text-align:right;">
50.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 31
</td>
<td style="text-align:left;">
01:39:44
</td>
<td style="text-align:left;">
Monday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1776.83 mins
</td>
<td style="text-align:right;">
29.61
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 39
</td>
<td style="text-align:left;">
23:03:05
</td>
<td style="text-align:left;">
Friday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1616.72 mins
</td>
<td style="text-align:right;">
26.95
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 28
</td>
<td style="text-align:left;">
02:54:06
</td>
<td style="text-align:left;">
Monday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1442.30 mins
</td>
<td style="text-align:right;">
24.04
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 39
</td>
<td style="text-align:left;">
04:39:53
</td>
<td style="text-align:left;">
Tuesday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1380.53 mins
</td>
<td style="text-align:right;">
23.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 39
</td>
<td style="text-align:left;">
06:40:33
</td>
<td style="text-align:left;">
Friday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1341.80 mins
</td>
<td style="text-align:right;">
22.36
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 39
</td>
<td style="text-align:left;">
23:44:13
</td>
<td style="text-align:left;">
Sunday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1324.10 mins
</td>
<td style="text-align:right;">
22.07
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 39
</td>
<td style="text-align:left;">
06:52:46
</td>
<td style="text-align:left;">
Friday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1323.92 mins
</td>
<td style="text-align:right;">
22.07
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 35
</td>
<td style="text-align:left;">
05:58:43
</td>
<td style="text-align:left;">
Saturday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1315.95 mins
</td>
<td style="text-align:right;">
21.93
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 31
</td>
<td style="text-align:left;">
05:54:50
</td>
<td style="text-align:left;">
Saturday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
1269.50 mins
</td>
<td style="text-align:right;">
21.16
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:durationLongTableFast">Table 2.7: </span>Duration of longest charge sequences (Fast charging)
</caption>
<thead>
<tr>
<th style="text-align:left;">
dvID
</th>
<th style="text-align:left;">
startTime
</th>
<th style="text-align:left;">
day_of_week
</th>
<th style="text-align:left;">
chargeType
</th>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:left;">
pairDuration
</th>
<th style="text-align:right;">
duration_hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Vehicle 43
</td>
<td style="text-align:left;">
22:51:43
</td>
<td style="text-align:left;">
Saturday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
922.03 mins
</td>
<td style="text-align:right;">
15.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 36
</td>
<td style="text-align:left;">
06:10:19
</td>
<td style="text-align:left;">
Wednesday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
865.70 mins
</td>
<td style="text-align:right;">
14.43
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 12
</td>
<td style="text-align:left;">
10:08:02
</td>
<td style="text-align:left;">
Thursday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
582.53 mins
</td>
<td style="text-align:right;">
9.71
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 40
</td>
<td style="text-align:left;">
01:37:03
</td>
<td style="text-align:left;">
Thursday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
398.27 mins
</td>
<td style="text-align:right;">
6.64
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 40
</td>
<td style="text-align:left;">
23:39:13
</td>
<td style="text-align:left;">
Tuesday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
346.25 mins
</td>
<td style="text-align:right;">
5.77
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 43
</td>
<td style="text-align:left;">
04:39:24
</td>
<td style="text-align:left;">
Tuesday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
227.85 mins
</td>
<td style="text-align:right;">
3.80
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 1
</td>
<td style="text-align:left;">
20:20:46
</td>
<td style="text-align:left;">
Thursday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
173.58 mins
</td>
<td style="text-align:right;">
2.89
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 19
</td>
<td style="text-align:left;">
13:52:01
</td>
<td style="text-align:left;">
Friday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
155.42 mins
</td>
<td style="text-align:right;">
2.59
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 49
</td>
<td style="text-align:left;">
01:40:40
</td>
<td style="text-align:left;">
Tuesday
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
116.37 mins
</td>
<td style="text-align:right;">
1.94
</td>
</tr>
<tr>
<td style="text-align:left;">
Vehicle 44
</td>
<td style="text-align:left;">
05:02:37
</td>
<td style="text-align:left;">
Monday
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
80.27 mins
</td>
<td style="text-align:right;">
1.34
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:shortDuration">2.5</a> shows the distribution of very short charging sequences. As we can see these appear to be generally less than 8 minutes in length for Standard Charges.</p>
<div class="figure"><span id="fig:shortDuration"></span>
<img src="EVBB_report_v2_files/figure-html/shortDuration-1.png" alt="Duration of charging sequences &lt; 15 minutes" width="672" />
<p class="caption">
Figure 2.5: Duration of charging sequences &lt; 15 minutes
</p>
</div>
<p>Manual inspection of the data showed that these short-duration ‘standard’ charging events generally occurred near the end of a longer-duration charging sequence. It appeared that once the vehicle had reached its highest state of charge, charging would intermittently stop and start again. This is probably due to the behaviour of the charger once the battery was almost full.</p>
<p>Table <a href="#tab:durationDescTableReduced">2.8</a> repeats the same descriptive statistics reported in Table <a href="#tab:durationDescTable">2.5</a> but for all sequences of greater than 8 minute duration. We can now see that the mean and median durations for both Standard and Fast Charge sequences are closer.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:durationDescTableReduced">Table 2.8: </span>Duration of charge sequences &gt; 8 minutes by charge type (minutes)
</caption>
<thead>
<tr>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:right;">
N
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:right;">
2807
</td>
<td style="text-align:left;">
251.15 mins
</td>
<td style="text-align:right;">
212.75
</td>
<td style="text-align:left;">
8.03 mins
</td>
<td style="text-align:left;">
3029.12 mins
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:right;">
316
</td>
<td style="text-align:left;">
31.89 mins
</td>
<td style="text-align:right;">
18.20
</td>
<td style="text-align:left;">
8.12 mins
</td>
<td style="text-align:left;">
922.03 mins
</td>
</tr>
</tbody>
</table>
<p>In addition to the many ‘short’ charging duration values, a small number of unreasonably long charging durations (longer than 14 hours for fast charging - see Table <a href="#tab:durationLongTableFast">2.7</a>) were calculated. As these exceeded the expected charge durations of even the highest capacity vehicles currently available, they were also assumed to be anomalies. The analyses in Section <a href="#duration">3.3</a> below was therefore made with the following charge events excluded from the data:</p>
<ul>
<li>duration &lt; 8 minutes for standard charging (4100 observations - noting that some of these may be short low power ‘fast charge’ events as discussed in Section <a href="#chargeType">2.3.1</a>)</li>
<li>duration &gt; 840 minutes (14 hours) for fast charging (2 observations)</li>
</ul>
<p>Figure <a href="#fig:longDuration">2.6</a> shows the distribution of charging sequences with the excessively long or short events removed. These charging durations appear more reasonable when considering standard battery capacities and available charge power.</p>
<div class="figure"><span id="fig:longDuration"></span>
<img src="EVBB_report_v2_files/figure-html/longDuration-1.png" alt="Duration of charging sequences with unreasonably long or short values removed" width="672" />
<p class="caption">
Figure 2.6: Duration of charging sequences with unreasonably long or short values removed
</p>
</div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:longDuration">Table 2.9: </span>Duration of charge sequences, final duration data
</caption>
<thead>
<tr>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:right;">
N
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:right;">
2807
</td>
<td style="text-align:left;">
251.15 mins
</td>
<td style="text-align:right;">
212.75
</td>
<td style="text-align:left;">
8.03 mins
</td>
<td style="text-align:left;">
3029.12 mins
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:right;">
425
</td>
<td style="text-align:left;">
20.49 mins
</td>
<td style="text-align:right;">
14.23
</td>
<td style="text-align:left;">
0.02 mins
</td>
<td style="text-align:left;">
582.53 mins
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="results" class="section level1">
<h1><span class="header-section-number">3</span> Results</h1>
<div id="time-of-charging" class="section level2">
<h2><span class="header-section-number">3.1</span> Time of charging</h2>
<p>It has been suggested that EV charging is more likely to occur in the early evening when drivers return from daily commutes or school pick-ups <span class="citation">(Langbroek, Franklin, and Susilo 2017)</span>. Figure <a href="#fig:chargeBeginsTime">3.3</a> uses a density plot to represent the proportion of charging and non-charging observations at different times of day by weekday vs weekends. The plot clearly shows non-charging during day-time use and also shows a bi-model distribution for fast charging (non-corrected categorisation). Standard charging also shows a bi-modal distribution with a peak around 22:00 on weekdays and another at 01:00 presumably indicating the use of timed or ‘smart’ charging or trickle events.</p>
<div class="figure"><span id="fig:chargeTime"></span>
<img src="EVBB_report_v2_files/figure-html/chargeTime-1.png" alt="Density plot of charging start times during weekdays" width="672" />
<p class="caption">
Figure 3.1: Density plot of charging start times during weekdays
</p>
</div>
<p>These patterns are also visible in Figure <a href="#fig:chargeTime">3.1</a> which shows the distribution of observed charging events by time of day and day of the week.</p>
<div class="figure"><span id="fig:chargeTimeDoW"></span>
<img src="EVBB_report_v2_files/figure-html/chargeTimeDoW-1.png" alt="Count of observed charging events by type, day of week and time" width="672" />
<p class="caption">
Figure 3.2: Count of observed charging events by type, day of week and time
</p>
</div>
<p>This figure indicates that the greatest frequency of standard charging events occur between the hours of 8pm and 8am, with very low occurrences of charging during morning and evening grid peaks. Fast charging on the other hand is a day-time activity on both weekdays and weekends.</p>
<p>To make the patterns of ‘initial charging’ clearer, we use just the ‘first’ charge observation in a pair (see above) and exclude automatic battery ‘top-ups’ (refer to Section <a href="#SoC">3.4</a>) by also filtering out any data where a charging observation begins while the state of charge is greater than 90%. Having done so, Figure <a href="#fig:chargeBeginsTime">3.3</a> uses a density plot to represent the proportion of charging events that begin at different times of the day on weekdays vs weekends for standard and fast charging (corrected classification).</p>
<div class="figure"><span id="fig:chargeBeginsTime"></span>
<img src="EVBB_report_v2_files/figure-html/chargeBeginsTime-1.png" alt="Density plot of charging start times during weekdays where state of charge &lt; 90%" width="672" />
<p class="caption">
Figure 3.3: Density plot of charging start times during weekdays where state of charge &lt; 90%
</p>
</div>
<p>As we can see, standard charging sequences (as opposed to single observations) have a noticeably different profile to charging patterns for fast charges. It suggests that the majority of standard charging events start at 22:00 and run overnight at home, and perhaps use the more powerful public charge points to top up during the day. However the plot also shows that this is not universal with a reasonable proportion of charging events starting earlier in the day, including during the NZ <a href="https://www.electrickiwi.co.nz/hour-of-power">peak demand periods</a> of 07:00 - 09:00 and 17:00 - 21:00.</p>
<p>Standard charging events were most likely to begin around 10pm during both weekdays and weekends. As it seems unlikely that this is due to vehicle drivers returning home at this hour, this effect may be due to drivers setting the charger on a timer to take advantage of cheaper “off-peak” electricity times, which frequently begin around 10pm.</p>
<p>Fast charging events were most likely to begin at 11:30am on weekdays and 1pm during weekends.</p>
</div>
<div id="patterns-of-power-demand" class="section level2">
<h2><span class="header-section-number">3.2</span> Patterns of power demand</h2>
<p>Given this distribution of charging events, it is important to understand their magnitude to understand the potential effect on the electricity network. Although we are hampered by the lack of ‘no charge’ data when the EV is not connected to the charger and switched off, this section analyses the patterns of power demand where charging is observed. Clearly this does not provide overall sample mean power demand which would include charging, non-charging <em>and</em> non-use observations.</p>
<p>Overall 75% of standard charging observations were 1.48 kW or more but the figure was 21.13 kW or more for fast charging.</p>
<p>Figure <a href="#fig:meanChargeByTimeStd">3.4</a> shows the mean power demand for standard charging observations by time of day and weekdays vs weekends for the selected time period. The plot uses transparency to indicate the number of EVs contributing to each of the mean calculations to give a guide to their reliability. Dots with stronger colours indicate means calculated from a larger number of EVs and, given the data gaps noted in Section <a href="#background">2.1</a>, this indicates patterns which are generally shared across more EVs.</p>
<p>This plot appears to show that there are three peaks in standard charging, one at 10:00, one at 18:00 (possibly based on fewer EVs) and one after midnight on weekdays. There are also noticeable 07:00 and 16:00 charging blips. On the other hand at weekends the daytime peak shifts to 14:00. Thus, while our previous analysis suggested that charging events were more likely to start later in the evening, the power demand of earlier charging events may actually be relatively high and co-incide with exisitng peak demand periods.</p>
<div class="figure"><span id="fig:meanChargeByTimeStd"></span>
<img src="EVBB_report_v2_files/figure-html/meanChargeByTimeStd-1.png" alt="Mean charging power demand (kW) by time of day" width="672" />
<p class="caption">
Figure 3.4: Mean charging power demand (kW) by time of day
</p>
</div>
<p>Fast charging however has no detectable pattern other than a clear increase in density during weekday daytimes (Figure <a href="#fig:meanChargeByTimeFast">3.5</a>).</p>
<div class="figure"><span id="fig:meanChargeByTimeFast"></span>
<img src="EVBB_report_v2_files/figure-html/meanChargeByTimeFast-1.png" alt="Mean charging power demand (kW) by time of day" width="672" />
<p class="caption">
Figure 3.5: Mean charging power demand (kW) by time of day
</p>
</div>
<p>It is possible that the ‘standard charge’ day-time peak is skewed by mis-classified short low power ‘fast charge’ observations (see Section <a href="#chargeType">2.3.1</a>). Figure <a href="#fig:medianChargeByTime">3.6</a> attempts to allow for this misclassification by plotting the median rather than the mean. The plot more clearly shows the 10:00 weekday spike which, if we assume that the mis-classified ‘fast charges’ will be skewing the standard charge mean value upwards, is likely to be due to mis-classified ‘fast charging’. However the 18:00 peak persists as does the 14:00 weekend peak while overnight charging levels are relatively stable as we would expect from <a href="#fig:meanChargeByTimeStd">3.4</a>.</p>
<div class="figure"><span id="fig:medianChargeByTime"></span>
<img src="EVBB_report_v2_files/figure-html/medianChargeByTime-1.png" alt="Median charging power demand (kW) by time of day" width="672" />
<p class="caption">
Figure 3.6: Median charging power demand (kW) by time of day
</p>
</div>
<p>Figure <a href="#fig:meanChargeByTimeMonth">3.7</a> repeats the median power-based analysis for ‘Standard charging’ but shows the results by month. While the sample size is probably too small to draw robust conclusions there appear to be differences between months with December showing few discernable peaks and September and January showing much lower daytime weekday charging. In addition, weekdays and weekends are much more similar in November and December.</p>
<div class="figure"><span id="fig:meanChargeByTimeMonth"></span>
<img src="EVBB_report_v2_files/figure-html/meanChargeByTimeMonth-1.png" alt="Median charging power demand (kW) by time of day and month" width="672" />
<p class="caption">
Figure 3.7: Median charging power demand (kW) by time of day and month
</p>
</div>
<p>On face value the results suggest that EVs could be placing additional power demand on local and national networks during well-known periods of peak demand although this appears to vary by month for this small sample of EV owners.</p>
<blockquote>
<p>Clearly this analysis should be revisited once the potential misclassification of ‘fast’ as ‘standard’ charging observations has been resolved and the ‘missing’ non-use (zero charging) observations have been imputed.</p>
</blockquote>
</div>
<div id="duration" class="section level2">
<h2><span class="header-section-number">3.3</span> Charging duration</h2>
<p>This section analyses the duration of observed charging events to understand when longer charging sequences are likely to occur. Table <a href="#tab:meanDurationTable">3.1</a> shows the mean durations for all all charging events by event start time for standard charging durations greater than 8 minutes (see Section <a href="#codeSequences">2.3.2</a>) and all fast charging events for observations collected after 01 October 2018.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:meanDurationTable">Table 3.1: </span>Mean duration of charge events by charge type (filtered data, corrected charge type)
</caption>
<thead>
<tr>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
median
</th>
<th style="text-align:left;">
min
</th>
<th style="text-align:left;">
max
</th>
<th style="text-align:right;">
sd
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
251.15 mins
</td>
<td style="text-align:left;">
212.75 mins
</td>
<td style="text-align:left;">
8.03 mins
</td>
<td style="text-align:left;">
3029.12 mins
</td>
<td style="text-align:right;">
199.34
</td>
</tr>
<tr>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
20.49 mins
</td>
<td style="text-align:left;">
14.23 mins
</td>
<td style="text-align:left;">
0.02 mins
</td>
<td style="text-align:left;">
582.53 mins
</td>
<td style="text-align:right;">
41.26
</td>
</tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:makeDurationTimeMean">Table 3.2: </span>Mean duration of charge sequences (values &gt; 480 minutes)
</caption>
<thead>
<tr>
<th style="text-align:left;">
qHour
</th>
<th style="text-align:left;">
chargeTypeCorrected
</th>
<th style="text-align:left;">
weekdays
</th>
<th style="text-align:left;">
meanDuration
</th>
<th style="text-align:right;">
nEVs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
04:45:00
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Weekdays
</td>
<td style="text-align:left;">
596.40 mins
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
21:00:00
</td>
<td style="text-align:left;">
Fast charging
</td>
<td style="text-align:left;">
Weekdays
</td>
<td style="text-align:left;">
582.53 mins
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
18:45:00
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Weekends
</td>
<td style="text-align:left;">
561.34 mins
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
18:15:00
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Weekends
</td>
<td style="text-align:left;">
533.46 mins
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
21:00:00
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Weekends
</td>
<td style="text-align:left;">
523.66 mins
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
10:30:00
</td>
<td style="text-align:left;">
Standard charging
</td>
<td style="text-align:left;">
Weekends
</td>
<td style="text-align:left;">
483.66 mins
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
</table>
<p>Figure <a href="#fig:durationTimeMean">3.8</a> plots the mean duration by time of day and weekday vs weekend and charge type. As before we use transparency to indicate the number of unique EVs contributing to the mean values and we have removed a small number of very large duration outliers (mean duration &gt; 540 minutes or 9 hours) which appears to be based on just 1 or 2 EVs (see Table @ref:(tab:makeDurationTimeMean)).</p>
<p>As we would expect, the plot shows that for standard charging mean ‘forward’ duration generally decreases from midnight, presumably as batteries are becoming fully charged through to 06:00 and then increases as the time of starting to charge increases through the day before trending downwards before midnight. Again, this confirms that charge events starting in or just after the evening peak demand period on both weekdays and weekends are likely to be longer, possibly reflecting the lower state of charge at this time of day (following use).</p>
<p>Duration of fast charge events by start time appear to be more randomly distributed, although very few events were recorded between midnight and 7am. This, along with the comparatively low number of recorded fast charge events indicated in Fig. <a href="#fig:obsPower">2.3</a> suggests that drivers utilize fast charging only “as necessary” to ensure they have enough battery capacity to complete their journey or when ‘at work’ or conducting some other mobility related task such as shopping.</p>
<div class="figure"><span id="fig:durationTimeMean"></span>
<img src="EVBB_report_v2_files/figure-html/durationTimeMean-1.png" alt="Mean duration (within quarter hours) by time of charging start" width="672" />
<p class="caption">
Figure 3.8: Mean duration (within quarter hours) by time of charging start
</p>
</div>
</div>
<div id="SoC" class="section level2">
<h2><span class="header-section-number">3.4</span> State of charge</h2>
<p>The state of charge is the percentage of energy still available to be used in the battery. In future, electric vehicles may be able to discharge any remaining battery charge as electricity into the grid, a process known as vehicle to grid (V2G) energy transfer. This may allow electric vehicles to have a net beneficial effect on the grid, reducing the evening peaks by providing electricity to the home during this period, and then recharging later in the evening or early the next morning when peak demand has diminished.</p>
<p>This section provides an indication of the state of charge of electric vehicles upon charging, so that the potential of V2G technology can be assessed.</p>
<div class="figure"><span id="fig:SoCplot1"></span>
<img src="EVBB_report_v2_files/figure-html/SoCplot1-1.png" alt="Value of state of charge (all charging observations)" width="672" />
<p class="caption">
Figure 3.9: Value of state of charge (all charging observations)
</p>
</div>
<p>As can be seen in Figure <a href="#fig:SoCplot1">3.9</a>, using the cleaned complete observations data, the state of charge for the majority of standard charge observations is above 90%. This is most likely due to the manner in which the charger regularly turns off and on again near the end of the charging cycle as described in Section <a href="#cleaning">2.2</a>.</p>
<p>Figure <a href="#fig:SoCplot2">3.10</a> shows the state of charge values for all charging events but with state of charge greater than 90% removed from the data for clarity. The figure indicates that many vehicles begin charging despite having greater than 50% charge remaining. This has clear implications for battery life management since continually top-up charging is known to substantially shorten the lifetime of EV batteries (XX ref needed XX). However it also indicates the potential to use the charge in the battery to feed into the grid, especially in the residential context.</p>
<div class="figure"><span id="fig:SoCplot2"></span>
<img src="EVBB_report_v2_files/figure-html/SoCplot2-1.png" alt="Value of state of charge (values &gt; 90% removed)" width="672" />
<p class="caption">
Figure 3.10: Value of state of charge (values &gt; 90% removed)
</p>
</div>
<p>Figure <a href="#fig:SoCplot3">3.11</a> repeats this analysis but uses the cleaned and corrected inferred start/end of charging sequence data instead of all charging observations. Figure <a href="#fig:SoCplot3">3.11</a> shows very similar distributions to the previous ‘all-observations’ plot (Figure <a href="#fig:SoCplot2">3.10</a>) and confirms that sequences of standard charging in particular most frequently start with battery state of charge over 50%.</p>
<div class="figure"><span id="fig:SoCplot3"></span>
<img src="EVBB_report_v2_files/figure-html/SoCplot3-1.png" alt="Value of state of charge at beginning of charging sequence (chargeType corrected, values &gt; 90% removed)" width="672" />
<p class="caption">
Figure 3.11: Value of state of charge at beginning of charging sequence (chargeType corrected, values &gt; 90% removed)
</p>
</div>
<div class="figure"><span id="fig:SoCplotTiming"></span>
<img src="EVBB_report_v2_files/figure-html/SoCplotTiming-1.png" alt="Mean state of charge at beginning of charge sequence by time of day (chargeType corrected, values &gt; 90% removed)" width="672" />
<p class="caption">
Figure 3.12: Mean state of charge at beginning of charge sequence by time of day (chargeType corrected, values &gt; 90% removed)
</p>
</div>
<p>Finally, Figure <a href="#fig:SoCplotTiming">3.12</a> shows the mean % charge by time of first charging observation in a sequence using the cleaned and corrected inferred start/end of charging sequence data. The plot suggests that this capacity may be relatively stable throughout the day albiet with slightly higher mean capacity around the morning peak as we would expect given over-night charging. It is unlikely that this early morning capacity would be willingly made available for V2G since the EV may be used in the near future although this may not always be the case. However it is interesting to note that mean capacity at start of charge in the evening peak period is still roughly 50% indicating relatively substantial power availability.</p>
</div>
</div>
<div id="summary" class="section level1">
<h1><span class="header-section-number">4</span> Summary</h1>
<p>Based on a relatively small and probably non-representative sample of 45 domestic electric vehicles provided by our research partner <a href="https://flipthefleet.org/">FlipTheFleet</a> and which were monitored from April 2018 to March 2019 we have found that:</p>
<ul>
<li><em>Power supplied</em>: The median power supplied during a charging event coded as ‘standard’ was 1.76 kW. The mean was slightly higher at 2.09 kW. Charging observations coded as ‘Fast’ had a median of 1.76 kW (mean = 2.09 kW). Mean power when charging showed a complex temporal profile for weekday standard charging (Figure <a href="#fig:meanChargeByTimeStd">3.4</a>) with a peak of ~ 2.5kw at 10:00 and a second of the same value at around 18:00 with further peaks just after midnight. The inverse is seen on weekends with a charge peak during the middle of the day;
<ul>
<li><em>Charging duration</em>: Charging durations tended to fall into one of two groups. Longer ‘standard’ charges had a median duration of 212.75 minutes and a mean duration of 251.1519772 minutes. High power ‘Fast’ charge events had a median duration of 14.2333333 minutes and a mean duration of 14.2333333 minutes;</li>
<li><em>Time of day</em>: Standard charging events tended to be the most frequent around 22:00 on both weekdays and weekends, suggesting the drivers in our dataset utilise timers to take advantage of off-peak electricity although this is not universal with a substantial proportion of charging events starting earlier in the day and potentially at higher power levels (see above). Fast charging events tended to begin at 11:30am on weekdays and 1pm during weekends;</li>
<li><em>State of charge</em>: As has been previously shown <span class="citation">(Speidel and Bräunl 2014)</span>, any drivers begin recharging with greater than 50% charge still remaining in the battery for both standard and fast charge events. This has clear implications both for the management of battery life and also for the potential for vehicle-to-grid power flows during peak demand periods where vehciles may be at or arriving home with substantial available charge.</li>
</ul></li>
</ul>
<p>In the data provided for this study, most charging occurs at home using either a 1.8kw or 3kW charger, and commonly occurs both in the evening peak period and through the night. In addition, many vehicles begin charging with significant battery capacity remaining, providing them with the ability to provide vehicle to grid energy transfer should that technology become widely available.</p>
<p>These preliminary findings support recent modelling work <span class="citation">(Concept Consulting 2018)</span> that suggests that any negative effects electric vehicles may have on the evening national electricity grid peaks should be mitigable through ‘smart’ charging methods. In addition, our analysis indicates that this may already be occurring to some extent in this sample of EV owners. If later adopters of electric vehicles can be induced to follow the same ‘smart’ charging patterns as those displayed in some of our data sample, it is likely that the effects that electric vehicles are otherwise likely to have on the electricity grid may be mitigated.</p>
</div>
<div id="statistical-annex" class="section level1">
<h1><span class="header-section-number">5</span> Statistical Annex</h1>
<div id="flip-the-fleet-data-description" class="section level2">
<h2><span class="header-section-number">5.1</span> Flip The Fleet data description</h2>
<div id="raw-data" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Raw data</h3>
<p>Data description for original data supplied (before processing or filtering).</p>
<pre class="r"><code>skimr::skim(rawDT)</code></pre>
<pre><code>## Skim summary statistics
##  n obs: 1882040 
##  n variables: 13 
## 
## ── Variable type:character ──────────────────────────────────────────────────────────────────────────────────
##    variable missing complete       n min max empty n_unique
##  chargeType       0  1882040 1882040  12  17     0        3
##        dvID       0  1882040 1882040   9  10     0       52
##          id       0  1882040 1882040  32  32     0       52
##    weekdays       0  1882040 1882040   8   8     0        2
## 
## ── Variable type:Date ───────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete       n        min        max     median
##      date       0  1882040 1882040 2018-04-05 2019-03-01 2018-11-25
##  n_unique
##       328
## 
## ── Variable type:difftime ───────────────────────────────────────────────────────────────────────────────────
##  variable missing complete       n    min        max     median n_unique
##     qHour       0  1882040 1882040 0 secs 85500 secs 44100 secs       96
##      time       0  1882040 1882040 0 secs 86399 secs 44877 secs    86400
## 
## ── Variable type:factor ─────────────────────────────────────────────────────────────────────────────────────
##     variable missing complete       n n_unique
##  day_of_week       0  1882040 1882040        7
##        month       0  1882040 1882040       12
##                                          top_counts ordered
##  Thu: 302335, Wed: 301324, Fri: 301212, Tue: 273804    TRUE
##  Nov: 332960, Oct: 309239, Dec: 299216, Jan: 291236   FALSE
## 
## ── Variable type:numeric ────────────────────────────────────────────────────────────────────────────────────
##         variable missing complete       n    mean      sd     p0     p25
##  charge_power_kw       0  1882040 1882040    1.59   63.73      0    0   
##      odometer_km 1255614   626426 1882040 7789.97 8268.44 -62920 2166.25
##      SoC_percent       0  1882040 1882040   69      20.66      0   56.31
##      p50      p75     p100     hist
##     1.3      1.85 74940.42 ▇▁▁▁▁▁▁▁
##  5309    11154    73607    ▁▁▁▇▇▁▁▁
##    70.41    83.05  1677.72 ▇▁▁▁▁▁▁▁
## 
## ── Variable type:POSIXct ────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete       n        min        max     median
##  dateTime       0  1882040 1882040 2018-04-05 2019-03-01 2018-11-25
##  n_unique
##   1784298</code></pre>
</div>
<div id="processedCheck" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Processed and cleaned data</h3>
<p>Data description for cleaned data (all observations).</p>
<pre class="r"><code>skimr::skim(cleanDT)</code></pre>
<pre><code>## Skim summary statistics
##  n obs: 1381565 
##  n variables: 17 
## 
## ── Variable type:character ──────────────────────────────────────────────────────────────────────────────────
##    variable missing complete       n min max empty n_unique
##  chargeFlag       3  1381562 1381565  17  25     0        5
##  chargeType       0  1381565 1381565  12  17     0        3
##        dvID       0  1381565 1381565   9  10     0       45
##          id       0  1381565 1381565  32  32     0       45
##  peakPeriod       0  1381565 1381565   8  12     0        3
##    weekdays       0  1381565 1381565   8   8     0        2
## 
## ── Variable type:Date ───────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete       n        min        max     median
##      date       0  1381565 1381565 2018-10-01 2019-02-27 2018-12-12
##  n_unique
##       150
## 
## ── Variable type:difftime ───────────────────────────────────────────────────────────────────────────────────
##      variable missing complete       n    min          max   median
##  dateTimeDiff      15  1381550 1381565 0 secs 2489602 secs  50 secs
##         qHour       0  1381565 1381565 0 secs   85500 secs 11:45:00
##     startTime       0  1381565 1381565 0 secs   86399 secs 12:22:46
##          time       0  1381565 1381565 0 secs   86399 secs 11:56:36
##  n_unique
##     13705
##        96
##     86400
##     86400
## 
## ── Variable type:factor ─────────────────────────────────────────────────────────────────────────────────────
##     variable missing complete       n n_unique
##  day_of_week       0  1381565 1381565        7
##        month       0  1381565 1381565        5
##                                          top_counts ordered
##  Wed: 218118, Thu: 215596, Fri: 209331, Mon: 207331    TRUE
##  Nov: 298332, Oct: 280869, Dec: 272272, Jan: 269868   FALSE
## 
## ── Variable type:numeric ────────────────────────────────────────────────────────────────────────────────────
##         variable missing complete       n    mean      sd     p0     p25
##  charge_power_kw       0  1381565 1381565    1.38    2.73      0    0   
##      odometer_km  957880   423685 1381565 7785.18 8623.97 -62920 2326   
##      SoC_percent      49  1381516 1381565   68.22   18.47      0   55.52
##      p50     p75     p100     hist
##     1.33    1.84    70.16 ▇▁▁▁▁▁▁▁
##  5157    9371    73607    ▁▁▁▇▆▂▁▁
##    69.45   81.95    98.1  ▁▁▂▃▆▇▇▆
## 
## ── Variable type:POSIXct ────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete       n        min        max     median
##  dateTime       0  1381565 1381565 2018-10-01 2019-02-27 2018-12-12
##  n_unique
##   1307878</code></pre>
<p>Data description for cleaned data (first observations in a charging sequence).</p>
<pre class="r"><code>skimr::skim(firstCleanDT)</code></pre>
<pre><code>## Skim summary statistics
##  n obs: 3232 
##  n variables: 22 
## 
## ── Variable type:character ──────────────────────────────────────────────────────────────────────────────────
##         variable missing complete    n min max empty n_unique
##       chargeFlag       0     3232 3232  25  25     0        1
##       chargeType       0     3232 3232  13  17     0        2
##  chargeTypeError       0     3232 3232  29  37     0        4
##             dvID       0     3232 3232   9  10     0       45
##          endType       0     3232 3232  13  17     0        2
##               id       0     3232 3232  32  32     0       45
##       peakPeriod       0     3232 3232   8  12     0        3
##         weekdays       0     3232 3232   8   8     0        2
## 
## ── Variable type:Date ───────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete    n        min        max     median n_unique
##      date       0     3232 3232 2018-10-01 2019-02-27 2018-12-05      140
## 
## ── Variable type:difftime ───────────────────────────────────────────────────────────────────────────────────
##      variable missing complete    n                   min
##  dateTimeDiff       0     3232 3232  0 secs              
##       endTime       0     3232 3232  1 secs              
##  pairDuration       0     3232 3232       0.01666667 mins
##         qHour       0     3232 3232  0 secs              
##     startTime       0     3232 3232 31 secs              
##          time       0     3232 3232 40 secs              
##                   max              median n_unique
##  230025 secs            309 secs              1782
##   86395 secs               46046.5 secs       3142
##         3029.117 mins        187.475 mins     2988
##   85500 secs          54900 secs                96
##   86392 secs               37250.5 secs       3100
##   86246 secs               55693.5 secs       3100
## 
## ── Variable type:factor ─────────────────────────────────────────────────────────────────────────────────────
##             variable missing complete    n n_unique
##  chargeTypeCorrected       0     3232 3232        2
##          day_of_week       0     3232 3232        7
##                month       0     3232 3232        5
##                              top_counts ordered
##      Sta: 2807, Fas: 425, Not: 0, NA: 0   FALSE
##  Fri: 490, Wed: 487, Thu: 486, Mon: 479    TRUE
##  Nov: 791, Oct: 743, Dec: 702, Feb: 564   FALSE
## 
## ── Variable type:numeric ────────────────────────────────────────────────────────────────────────────────────
##         variable missing complete    n    mean      sd        p0     p25
##  charge_power_kw       0     3232 3232    6.8    12.24      0.5     1.59
##      odometer_km    2510      722 3232 6975.73 8088.03 -52352    1875   
##      SoC_percent       0     3232 3232   48.95   18.21      4.11   35.84
##      p50     p75     p100     hist
##     2.09    3.31    70.16 ▇▁▁▁▁▁▁▁
##  4396    9279.75 54443    ▁▁▁▂▇▁▁▁
##    47.78   59.31    98.1  ▁▃▇▇▇▃▁▂
## 
## ── Variable type:POSIXct ────────────────────────────────────────────────────────────────────────────────────
##  variable missing complete    n        min        max     median n_unique
##  dateTime       0     3232 3232 2018-10-01 2019-02-27 2018-12-05     3232</code></pre>
</div>
</div>
<div id="coding-checks" class="section level2">
<h2><span class="header-section-number">5.2</span> Coding checks</h2>
<div id="chargeFlagTest" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Charge flag</h3>
<p>This is used to identify observations that form part of a sequence. The logic is given in Section <a href="#codeSequences">2.3.2</a>. Here we show the results of applying an additional 120 second rule. In this case a sequence only exists where we have charging observations which have less than 120 seconds between them.</p>
<pre class="r"><code>#kableExtra::kable(sequenceMethod1_T, caption = &quot;Charge sequence flags (120 second rule)&quot;) #%&gt;%
#  kable_styling()

#kableExtra::kable(sequenceMethod2_T, caption = &quot;Charge sequence flags (no 120 second rule)&quot;) %&gt;%
#  kable_styling()</code></pre>
<p>As we can see, applying the 120 second rule reduces the number of observations categorised as part of a sequence as it will not know what to do with:</p>
<ul>
<li>charge -&gt; gap of &gt; 120 secs -&gt; charge <gap of > 120 secs -&gt; charge</li>
</ul>
<p>For now we therefore do not use the 120 second rule.</p>
<pre class="r"><code># Check chargeFlag ----
message(&quot;chargeFlag is used to classify charging events - check against charge type:&quot;)</code></pre>
<pre><code>## chargeFlag is used to classify charging events - check against charge type:</code></pre>
<pre class="r"><code>t &lt;- table(cleanDT$chargeFlag, cleanDT$chargeType, useNA = &quot;always&quot;)
kableExtra::kable(t, caption = &quot;chargeFlag errors (clean data)&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:checkChargeFlags">Table 5.1: </span>chargeFlag errors (clean data)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Fast charging
</th>
<th style="text-align:right;">
Not charging
</th>
<th style="text-align:right;">
Standard charging
</th>
<th style="text-align:right;">
NA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Charging in a seq
</td>
<td style="text-align:right;">
6555
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
778592
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
First charge obs in a seq
</td>
<td style="text-align:right;">
413
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6928
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Last charge in a seq
</td>
<td style="text-align:right;">
350
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6992
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Not charging (0 kW)
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
576491
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Single charge observation
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5111
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>message(&quot;There are a few observations that have chargeFlag = NA but are charging... why?&quot;)</code></pre>
<pre><code>## There are a few observations that have chargeFlag = NA but are charging... why?</code></pre>
<p>We also test the patterns of charging that this classification produces. We do this first for ‘standard’ charging sequences and then for ‘fast’ charging sequences.</p>
<pre class="r"><code># debug sequences visually ----

# start &amp; end charge rate ----
firstLastDT &lt;- firstLastDT[, startChargekW := charge_power_kw]
firstLastDT &lt;- firstLastDT[, endChargekW := shift(charge_power_kw, type = &quot;lead&quot;)]

# start &amp; end batter state
firstLastDT &lt;- firstLastDT[, startSoC_pc := SoC_percent]
firstLastDT &lt;- firstLastDT[, endSoC_pc := shift(SoC_percent, type = &quot;lead&quot;)]

# calc duration so we can decide what to do where it is -ve - i.e. event spanned midnight ----
firstLastDT &lt;- firstLastDT[, notDuration := difftime(endTime, startTime, units=&#39;mins&#39;), by = id] # set all within id, if this is -ve then it spanned midnight
# fix # 1
firstLastDT &lt;- firstLastDT[, endTimeTrunc := ifelse(notDuration &lt; 0, 
                                                   hms::parse_hm(&quot;23:59&quot;),
                                                   endTime)] # this truncates charge periods that span midnight and ends then at midnight for clarity. Of course this makes a hash of early morning charging patterns... 

# charge rate &amp; state of charge deltas ----
firstLastDT &lt;- firstLastDT[, chargePowerDelta := endChargekW - charge_power_kw] # should be -ve where we start high and end low
firstLastDT &lt;- firstLastDT[, SoC_pcDelta := endSoC_pc - startSoC_pc] # should be -ve where we start high and end low</code></pre>
<p>Figure <a href="#fig:checkStdSequenceskW">5.1</a> plots the first and last charge observation in a sequence for all pairs and for all vehicles where events were classified as (corrected) ‘standard’ charges. The y value is charging rate (kW) at the start and end of the sequence. Colour (red end of the scale) is used to highlight pairs which show an ‘odd’ pattern - e.g. the charge rate increased.</p>
<pre class="r"><code># format labels function
# https://stackoverflow.com/questions/53804629/how-to-format-difftime-as-hhmm-in-ggplot2
format_hm &lt;- function(sec) stringr::str_sub(format(sec), end = -4L)
# plotting function
makeSeqChargePlot &lt;- function(dt, y = y, yend = yend, colour = colour){
  p &lt;- ggplot2::ggplot(dt) +
    geom_segment(aes(x = hms::as.hms(startTime), # start x value
                     xend = hms::as.hms(endTimeTrunc), # end x value
                     y = get(y), # start y value
                     yend = get(yend), # end y value
                     colour = get(colour))) + # colour to highlight some value
    labs(x = &quot;Sequence start and end time&quot;) + 
    theme(legend.position = &quot;bottom&quot;) +
    scale_x_time(labels = format_hm) +
    facet_wrap(. ~ dvID)
  return(p)
}

dt &lt;- firstLastDT[chargeTypeCorrected %like% &quot;Standard&quot; &amp; 
                    #startChargekW &lt; 5 &amp; #use this to filter out the few that seem to have 6kW chargers (they could also be mis-coded &#39;fast&#39; charging)
                    chargeFlag %like% &quot;First&quot;]

p &lt;- makeSeqChargePlot(dt, y = &quot;startChargekW&quot;, 
                       yend = &quot;endChargekW&quot;, 
                       colour =  &quot;chargePowerDelta&quot;) 
p &lt;- p + 
  labs(y = &quot;Charging rate (kW)&quot;,
       caption = &quot;Standard charging (corrected) \n 
       Pairs spanning midnight truncated at 23:59 \n
       Peak periods shaded&quot;) +
  guides(colour = guide_legend(title = &quot;Charge rate delta (kW)&quot;)) +
  scale_color_continuous(low = &quot;green&quot;, high = &quot;red&quot;) # highlight ones that went up
yMin &lt;- min(dt$startChargekW) # might not quite work if end is higher...
yMax &lt;- max(dt$startChargekW) # might not quite work if end is higher...
addPeaks(p)</code></pre>
<div class="figure"><span id="fig:checkStdSequenceskW"></span>
<img src="EVBB_report_v2_files/figure-html/checkStdSequenceskW-1.png" alt="Standard charging (corrected) - rate of charge" width="672" />
<p class="caption">
Figure 5.1: Standard charging (corrected) - rate of charge
</p>
</div>
<pre class="r"><code>#ggsave(&quot;plots/standardChargePairs_kW_LineSegments.png&quot;, p, height = 10)</code></pre>
<p>Figure <a href="#fig:stdPowerDeltaDensity">5.2</a> shows the distribution of charge power deltas by peak/not peak period (of start time) for ‘standard’ charge events. This suggests that the majority of charging events either hold power constant or decline over time with some sort of shoulder effect. A few increase. More of those which start in the ‘evening’ and ‘not peak’ period seem to hold the power level constant, presumably because the battery capacity is slightly lower at this time following day-time use.</p>
<pre class="r"><code>p &lt;- ggplot2::ggplot(dt, aes(x = chargePowerDelta, colour = peakPeriod)) +
  geom_density(alpha = 0.5) +
  guides(colour = guide_legend(title = &quot;Peak period:&quot;)) +
  labs(x = &quot;Change in power from start to end (kW)&quot;)
p</code></pre>
<div class="figure"><span id="fig:stdPowerDeltaDensity"></span>
<img src="EVBB_report_v2_files/figure-html/stdPowerDeltaDensity-1.png" alt="Histogram of charge power deltas by peak/not peak period" width="672" />
<p class="caption">
Figure 5.2: Histogram of charge power deltas by peak/not peak period
</p>
</div>
<p>Figure <a href="#fig:checkStdSequencesSoC">5.3</a> uses the same approach but in this case the y value is charging rate (kW) at the start and end of the sequence. Colour (red end of the scale) is used to highlight pairs which show an ‘odd’ pattern - e.g. the battery state of charge decreased.</p>
<pre class="r"><code>#dt &lt;- dt[, SoC_pcDelta := SoC_pcDelta * -1] # invert so big drops become red in plot
p &lt;- makeSeqChargePlot(dt, y = &quot;startSoC_pc&quot;, 
                       yend = &quot;endSoC_pc&quot;, 
                       colour =  &quot;SoC_pcDelta&quot;)
p &lt;- p + 
  labs(y = &quot;State of charge (%)&quot;,
       caption = &quot;Standard charging (corrected) \n Pairs spanning midnight truncated at 23:59&quot;) +
  guides(colour = guide_legend(title = &quot;State of charge delta (%)&quot;)) +
  scale_color_continuous(low = &quot;red&quot;, high = &quot;green&quot;) # highlight ones that went down
yMin &lt;- min(dt$startSoC_pc) # might not quite work if end is higher...
yMax &lt;- max(dt$startSoC_pc) # might not quite work if end is higher...
addPeaks(p)</code></pre>
<div class="figure"><span id="fig:checkStdSequencesSoC"></span>
<img src="EVBB_report_v2_files/figure-html/checkStdSequencesSoC-1.png" alt="Standard charging (corrected) - state of charge" width="672" />
<p class="caption">
Figure 5.3: Standard charging (corrected) - state of charge
</p>
</div>
<pre class="r"><code>#ggsave(&quot;plots/standardChargePairs_SoC_LineSegments.png&quot;, p, height = 10)</code></pre>
<p>Figure <a href="#fig:checkFastSequenceskW">5.4</a> and Figure <a href="#fig:checkFastSequencesSoC">5.5</a> repeat these plots but for (corrected) ‘fast’ charge events.</p>
<pre class="r"><code>dt &lt;- firstLastDT[chargeTypeCorrected %like% &quot;Fast&quot; &amp; 
                    #startChargekW &lt; 5 &amp; #use this to filter out the few that seem to have 6kW chargers (or they might be &#39;fast&#39; charging too)
                    chargeFlag %like% &quot;First&quot;]

p &lt;- makeSeqChargePlot(dt, y = &quot;startChargekW&quot;, 
                       yend = &quot;endChargekW&quot;, 
                       colour =  &quot;chargePowerDelta&quot;) 
p &lt;- p + 
  labs(y = &quot;Charging rate (kW)&quot;,
       caption = &quot;Fast charging (corrected) \n Pairs spanning midnight truncated at 23:59&quot;) +
  guides(colour = guide_legend(title = &quot;Charge rate delta (kW)&quot;)) +
  scale_color_continuous(low = &quot;green&quot;, high = &quot;red&quot;) # highlight ones that went up
yMin &lt;- min(dt$startChargekW) # might not quite work if end is higher...
yMax &lt;- max(dt$startChargekW) # might not quite work if end is higher...
addPeaks(p)</code></pre>
<div class="figure"><span id="fig:checkFastSequenceskW"></span>
<img src="EVBB_report_v2_files/figure-html/checkFastSequenceskW-1.png" alt="Fast charging (corrected) - rate of charge" width="672" />
<p class="caption">
Figure 5.4: Fast charging (corrected) - rate of charge
</p>
</div>
<pre class="r"><code>#ggsave(&quot;plots/fastChargePairs_kW_LineSegments.png&quot;, p, height = 10)</code></pre>
<pre class="r"><code>#dt &lt;- dt[, SoC_pcDelta := SoC_pcDelta * -1] # invert so big drops become red in plot
p &lt;- makeSeqChargePlot(dt, y = &quot;startSoC_pc&quot;, 
                       yend = &quot;endSoC_pc&quot;, 
                       colour =  &quot;SoC_pcDelta&quot;)
p &lt;- p + 
  labs(y = &quot;State of charge (%)&quot;,
       caption = &quot;Fast charging (corrected) \n Pairs spanning midnight truncated at 23:59&quot;) +
  guides(colour = guide_legend(title = &quot;State of charge delta (%)&quot;)) +
  scale_color_continuous(low = &quot;red&quot;, high = &quot;green&quot;) # highlight ones that went down
yMin &lt;- min(dt$startSoC_pc) # might not quite work if end is higher...
yMax &lt;- max(dt$startSoC_pc) # might not quite work if end is higher...
addPeaks(p)</code></pre>
<div class="figure"><span id="fig:checkFastSequencesSoC"></span>
<img src="EVBB_report_v2_files/figure-html/checkFastSequencesSoC-1.png" alt="Fast charging (corrected) - state of charge" width="672" />
<p class="caption">
Figure 5.5: Fast charging (corrected) - state of charge
</p>
</div>
<pre class="r"><code>#ggsave(&quot;plots/fastChargePairs_SoC_LineSegments.png&quot;, p, height = 10)</code></pre>
<p>Figure <a href="#fig:fastPowerDeltaDensity">5.6</a> shows the distribution of charge power deltas by peak/not peak period (of start time) for all ‘fast’ charge events. These show a rather different pattern.</p>
<pre class="r"><code>p &lt;- ggplot2::ggplot(dt, aes(x = chargePowerDelta, colour = peakPeriod)) +
  geom_density(alpha = 0.5) +
  guides(colour = guide_legend(title = &quot;Peak period:&quot;)) +
  labs(x = &quot;Change in power from start to end (kW)&quot;)
p</code></pre>
<div class="figure"><span id="fig:fastPowerDeltaDensity"></span>
<img src="EVBB_report_v2_files/figure-html/fastPowerDeltaDensity-1.png" alt="Histogram of charge power deltas by peak/not peak period" width="672" />
<p class="caption">
Figure 5.6: Histogram of charge power deltas by peak/not peak period
</p>
</div>
</div>
<div id="charge-type" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Charge type</h3>
<p><code>chargeType</code> is used to classify charging events into standard vs fast using the 7 kW threshold. But there may be misclassfications where a sequence starts on a fast charger but power demand declines below the threshold. We can check this and have corrected it in some sections above using the start/end pairs.</p>
<pre class="r"><code># Check chargeType ----

t &lt;- table(firstLastDT$chargeTypeError, firstLastDT$chargeType, useNA = &quot;always&quot;)

kableExtra::kable(t, caption = &quot;chargeType errors detected&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:checkChargeType">Table 5.2: </span>chargeType errors detected
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Fast charging
</th>
<th style="text-align:right;">
Standard charging
</th>
<th style="text-align:right;">
NA
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Error: first = Fast, last = Standard
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Error: first = Standard, last = Fast
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
OK: first = Fast, last = Fast
</td>
<td style="text-align:right;">
336
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
OK: first = Standard, last = Standard
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6913
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
350
</td>
<td style="text-align:right;">
6992
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>nError &lt;- nrow(firstLastDT[chargeTypeError %like% &quot;Error&quot;])
nErrorEVs &lt;- uniqueN(firstLastDT[chargeTypeError %like% &quot;Error&quot;]$dvID)  
message(&quot;There are &quot;, nError, &quot; pairs (out of a total of &quot;, nrow(firstLastDT)/2,&quot;) from &quot;, nErrorEVs ,&quot; EVs where charge type doesn&#39;t match.&quot;)</code></pre>
<pre><code>## There are 92 pairs (out of a total of 7341.5) from 26 EVs where charge type doesn&#39;t match.</code></pre>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-Azadfar2015">
<p>Azadfar, Elham, Victor Sreeram, and David Harries. 2015. “The investigation of the major factors influencing plug-in electric vehicle driving patterns and charging behaviour.” <em>Renewable and Sustainable Energy Reviews</em> 42: 1065–76. <a href="https://doi.org/10.1016/j.rser.2014.10.058">https://doi.org/10.1016/j.rser.2014.10.058</a>.</p>
</div>
<div id="ref-ConceptConsulting2018">
<p>Concept Consulting. 2018. “‘ Driving change ’ – Issues and options to maximise the opportunities from large-scale electric vehicle uptake in New Zealand,” no. March.</p>
</div>
<div id="ref-Eyers2018">
<p>Eyers, Lisa. 2018. “Electric Chargepoint Analysis 2017 : Domestics Key findings :” no. December.</p>
</div>
<div id="ref-Khan2018">
<p>Khan, Imran, Michael W. Jack, and Janet Stephenson. 2018. “Analysis of greenhouse gas emissions in electricity systems using time-varying carbon intensity.” <em>Journal of Cleaner Production</em> 184: 1091–1101. <a href="https://doi.org/10.1016/j.jclepro.2018.02.309">https://doi.org/10.1016/j.jclepro.2018.02.309</a>.</p>
</div>
<div id="ref-langbroek_when_2017">
<p>Langbroek, Joram H. M., Joel P. Franklin, and Yusak O. Susilo. 2017. “When Do You Charge Your Electric Vehicle? A Stated Adaptation Approach.” <em>Energy Policy</em> 108 (September): 565–73. <a href="https://doi.org/10.1016/j.enpol.2017.06.023">https://doi.org/10.1016/j.enpol.2017.06.023</a>.</p>
</div>
<div id="ref-li_review_2017">
<p>Li, Wenbo, Ruyin Long, Hong Chen, and Jichao Geng. 2017. “A Review of Factors Influencing Consumer Intentions to Adopt Battery Electric Vehicles.” <em>Renewable and Sustainable Energy Reviews</em> 78 (October): 318–28. <a href="https://doi.org/10.1016/j.rser.2017.04.076">https://doi.org/10.1016/j.rser.2017.04.076</a>.</p>
</div>
<div id="ref-rezvani_advances_2015">
<p>Rezvani, Zeinab, Johan Jansson, and Jan Bodin. 2015. “Advances in Consumer Electric Vehicle Adoption Research: A Review and Research Agenda.” <em>Transportation Research Part D: Transport and Environment</em> 34 (January): 122–36. <a href="https://doi.org/10.1016/j.trd.2014.10.010">https://doi.org/10.1016/j.trd.2014.10.010</a>.</p>
</div>
<div id="ref-speidel_driving_2014">
<p>Speidel, Stuart, and Thomas Bräunl. 2014. “Driving and Charging Patterns of Electric Vehicles for Energy Usage.” <em>Renewable and Sustainable Energy Reviews</em> 40 (December): 97–110. <a href="https://doi.org/10.1016/j.rser.2014.07.177">https://doi.org/10.1016/j.rser.2014.07.177</a>.</p>
</div>
<div id="ref-Stephenson2017">
<p>Stephenson, Janet, Rebecca Ford, Nirmal-Kumar Nair, Neville Watson, Alan Wood, and Allan Miller. 2017. “Smart grid research in New Zealand – A review from the GREEN Grid research programme.” <a href="https://doi.org/10.1016/j.rser.2017.07.010">https://doi.org/10.1016/j.rser.2017.07.010</a>.</p>
</div>
<div id="ref-TranspowerNZ2015">
<p>Transpower New Zealand. 2015. “Transmission Planning Report,” no. July: 320.</p>
</div>
<div id="ref-TranspowerNewZealand2017">
<p>———. 2017. “Battery Storage in New Zealand,” no. September: 41. <a href="https://www.transpower.co.nz/sites/default/files/publications/resources/Battery%20Storage%20in%20New%20Zealand.pdf">https://www.transpower.co.nz/sites/default/files/publications/resources/Battery Storage in New Zealand.pdf</a>.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
